In [7]:
import numpy as np
import scipy.linalg as linalg

In [4]:
A = np.array([[2, 1, 1], [1,3,2], [1,0,0]])

In [5]:
B = np.array([4, 5, 6])

In [10]:
ans = np.linalg.solve(A, B)
ans

array([  6.,  15., -23.])

In [8]:
LU = linalg.lu_factor(A)
x = linalg.lu_solve(LU, B)
# need to use lu_solve to solve a lower/upper transformed matrix

In [9]:
x

array([  6.,  15., -23.])

trying out cholskey

In [22]:
Aa = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]])
Bb = np.array([6., 25., -11., 15.])

In [23]:
aa_lower = np.linalg.cholesky(A)

In [25]:
np.dot(aa_lower, aa_lower.T.conj()) 

array([[10., -1.,  2.,  0.],
       [-1., 11., -1.,  3.],
       [ 2., -1., 10., -1.],
       [ 0.,  3., -1.,  8.]])

In [26]:
Aa

array([[10., -1.,  2.,  0.],
       [-1., 11., -1.,  3.],
       [ 2., -1., 10., -1.],
       [ 0.,  3., -1.,  8.]])

qr decomp

In [29]:
A = np.array([
       [2., 1., 1.],
       [1., 3., 2.],
       [1., 0., 0]])
B = np.array([4., 5., 6.])
Q, R = linalg.qr(A)  # QR decomposition
y = np.dot(Q.T, B)  # Let y=Q'.B
x = linalg.solve(R, y)  # Solve Rx=y

gauss steigel

In [34]:
def gauss(A,B, n, tol = 1 * 2**-12):
    l = np.tril(A)
    U = A - l
    l_inv = np.linalg.inv(l)
    x = np.zeros_like(B)
    
    for i in range(n):
        Ux = np.dot(U, x) # np.dot for matrix multiplication
        x_new = np.dot(l_inv, B - Ux) #solving for x with the equatio
        if np.allclose(x, x_new, tol):
            break
        x = x_new
        
    return x
        

In [35]:
gauss(Aa, Bb, 100)

array([ 1.00009128,  2.00002134, -1.00003115,  0.9999881 ])